source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:
  - 'README.md'
  - 'util'
  - 'config'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'Procfile'
  - 'Rakefile'
  - 'vendor'
  - 'config.ru'
  - 'unicorn.rb'
  - 'fabfile.py'
  - 'node_modules'
  - 'bower_components'
  - 'package.json'
  - 'bower.json'
  - 'Gruntfile.js'
  - 'assets/_css'
  - 'assets/_less'
keep_files:
  - '.git'
  - '.svn'
gems:        []
timezone:    nil
encoding:    utf-8

future:      true
show_drafts: false
limit_posts: 0
highlighter: pygments

relative_permalinks: true
permalink: "/posts/:title"

markdown:      kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
textile_ext:   textile

excerpt_separator: "\n\n"

safe:        false
host:        0.0.0.0
port:        4000
baseurl:     /
url:         http://localhost:4000
lsi:         false

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
  fenced_code_blocks: true

rdiscount:
  extensions:
    - 'smart'

redcarpet:
  extensions: []

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false
  input: GFM

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true
